# NUMPY


## Ejercicio 1.0

Importamos numpy

In [1]:
import numpy as np

## Ejercicio 1.1

Repaso de arrays

In [49]:
#arreglo unidimensional
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) #le paso una lista y crea el array

In [50]:
print(array1)

[1 2 3 4 5 6 7 8 9]


In [51]:
type(array1)

numpy.ndarray

In [52]:
array2 = np.array([1, 2, 3, 4, 5, 6, 10, 11, 12])

In [53]:
print(array1 + array2)

[ 2  4  6  8 10 12 17 19 21]


In [54]:
#matriz de 2x2 bidimensional
matriz1 = np.array([
    [1,2],
    [3,4]
])

In [55]:
print(matriz1)

[[1 2]
 [3 4]]


In [56]:
#matriz 4x3
matriz2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(matriz2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [57]:
#matriz 2x5
matriz3 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print(matriz3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Ejercicio 1.2

Operaciones con matrices

In [58]:
matrizA = np.array([[1,2],[3,4]])

In [59]:
matrizB = np.array([[1,2],[3,4]])

In [60]:
#con matmul puedo calcular el producto de dos arrays
print(np.matmul(matrizA, matrizB))

[[ 7 10]
 [15 22]]


In [61]:
#podemos crear la matriz traspuesta utilizando transpose()
matriz_original = np.array([[1,2,3,4], [5,6,7,8]])
print(matriz_original)

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
matriz_traspuesta = np.transpose(matriz_original)

print(matriz_traspuesta)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Ejercicio 1.3

Calcular el determinante de una matriz

In [63]:
matriz1 = np.array([[1,2],[3,4]])

In [64]:
determinante = np.linalg.det(matriz1)

In [65]:
print(matriz1)
print(determinante)

[[1 2]
 [3 4]]
-2.0000000000000004


## Ejercicio 1.4

Resolvemos ecuaciones lineales usando numpy

5*X + 6*Y = 20

3*X + 8*Y = 34


In [66]:
coeficientes = np.array([
    [5,6],
    [3,8]
])

ordenadas = np.array([20,34])

In [67]:
solucion = np.linalg.solve(coeficientes, ordenadas)
print(solucion)

[-2.  5.]


In [68]:
print(f"El valor de X es {round(solucion[0])}")
print(f"El valor de Y es {round(solucion[1])}")

El valor de X es -2
El valor de Y es 5


## Ejercicio 1.5

Vamos a trabajar con una matriz de tres dimensiones

In [69]:
#creo la matriz de tres dimensiones
matriz_multidimensiones = np.array([
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [16,17,18,19],
            [20,21,22,23]
        ],
        [
            [24,25,26,27],
            [28,29,30,31],
            [32,33,34,35]
        ]
    ])

In [70]:
print(matriz_multidimensiones) #imprimo la matriz de tres dimensiones

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [71]:
#imprimo los valores de la matriz
matriz_multidimensiones[0, 0, 0] #[submatriz/pagina, fila, columna]

1

In [72]:
matriz_multidimensiones[0, 0, 2]

3

In [73]:
matriz_multidimensiones[0, 2, 1]

10

In [74]:
matriz_multidimensiones[2, 1, 3]

31

In [75]:
matriz_multidimensiones[1, 1, 0]

16

In [76]:
matriz_multidimensiones[2, 2, 2]

34

## Ejercicio 1.6

Podemos saber la cantidad de dimensiones que tiene cualquier arreglo

`np.ndim(matriz)`

`matriz.ndim`

In [77]:
np.ndim(matriz_multidimensiones)

3

In [78]:
matriz_multidimensiones.ndim

3

## Ejercicio 1.7

Podemos conocer la forma del array

`np.shape(matriz)`

`matriz.shape`

In [79]:
np.shape(matriz_multidimensiones) #paginas/submatriz, filas, columnas

(3, 3, 4)

In [80]:
matriz_multidimensiones.shape

(3, 3, 4)

## Ejercicio 1.8

Podemos ver la cantidad de elementos de un array

`np.size(matriz)`

`matriz.size`

In [81]:
np.size(matriz_multidimensiones)

36

In [82]:
matriz_multidimensiones.size

36

## Ejercicio 1.9

Vamos a crear o recortar un nuevo array a partir de uno existente usando los indices

In [83]:
array_unidimensional = np.array([1,2,3,5,1,5,3,7,3,8,3,6,3,7,2,6,7,2,6,7,2,5,6,7,2])

In [84]:
print(array_unidimensional)

[1 2 3 5 1 5 3 7 3 8 3 6 3 7 2 6 7 2 6 7 2 5 6 7 2]


In [85]:
array_unidimensional[0]

1

In [86]:
array_unidimensional[1]

2

In [87]:
array_unidimensional[-1]

2

In [88]:
array_unidimensional[-3]

6

In [89]:
array_unidimensional[0:4] #de la posicion 0 a la 4 (sin incluir el de la posicion 4) 

array([1, 2, 3, 5])

In [90]:
array_unidimensional[3:] #trae todo desde la posicion 3 y hacia la derecha

array([5, 1, 5, 3, 7, 3, 8, 3, 6, 3, 7, 2, 6, 7, 2, 6, 7, 2, 5, 6, 7, 2])

In [91]:
array_unidimensional[-3:] #los último tres valores

array([6, 7, 2])

In [92]:
array_unidimensional[:5] #trae hasta la posicion de llegada (del inicio hasta la posicion 5 sin inlcuirla, lo de la izquierda)

array([1, 2, 3, 5, 1])

In [93]:
array_unidimensional[:-10]

array([1, 2, 3, 5, 1, 5, 3, 7, 3, 8, 3, 6, 3, 7, 2])

## Ejercicio 1.10

Ordenar el array de forma ascendente, es decir de menor a mayor

`np.sort(array_desordenado)`

In [6]:
array_desordenado = np.array([5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10])

In [7]:
array_ascendente = np.sort(array_desordenado)

In [8]:
print(array_ascendente)

[-10  -7  -6  -6  -5  -3  -2  -2  -1   0   1   2   3   3   4   4   5   5
   7   8   9  10  12  12  14  15  20]


## Ejercicio 1.11

Puedo reordenar el array en función de los índices, los valores que estaban primeros pasan a estar últimos y los que estaban últimos pasan a estar primeros

`np.flip(mi_array)`

In [11]:
array_desordenado = np.array([5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10])

In [12]:
array_invertido = np.flip(array_desordenado)
print(array_invertido)

[ 10  -2   8   2   3   7  -5   4   0  -1  -6  20  15  14  12 -10   3  -3
   1   5  -6  12  -7   9  -2   4   5]


## Ejercicio 1.12

Vamos a crear un array con números aleatorios

`np.random.default_rng()`

In [14]:
rng = np.random.default_rng() #construsctor

In [15]:
#arrays con valores aleatorios entre 0 y 1
rng.random(3)

array([0.0910646 , 0.15354156, 0.53167089])

In [16]:
rng.random(5)

array([0.90373329, 0.80621267, 0.816326  , 0.21317983, 0.91132532])

In [18]:
#arrays con valores aleatorios entre números enteros
rng.integers(1,11,6) #valor mínimo inlcuisivo, valor máximo exclusivo, size

array([ 9, 10,  8,  3,  5,  2])

In [20]:
rng.integers(-5,15,[4,3]) #matriz 4x3

array([[ 4,  1,  9],
       [-5, -4,  2],
       [13, 12,  9],
       [ 1, 12, -3]])

In [21]:
rng.integers(-20,100,[2,4,3]) #2 paginas, 4 filas, 3 columnas

array([[[ 70,  57,  99],
        [ 32,  32,  42],
        [ 15,  99,  90],
        [-11,   3,  75]],

       [[ -8,  40,  95],
        [ -1,  50,  72],
        [ 13,  43,  34],
        [ 80,  -2,  53]]])

## Ejercicio 1.13

Generar un array con números aleatorios elegidos desde otro array

`rng.choice(array, cantidad_elementos)`

In [24]:
array_base = [5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10]
print(array_base)

[5, 4, -2, 9, -7, 12, -6, 5, 1, -3, 3, -10, 12, 14, 15, 20, -6, -1, 0, 4, -5, 7, 3, 2, 8, -2, 10]


In [25]:
array_generado = rng.choice(array_base, 3)
print(array_generado)

[ 2 -7  5]


In [26]:
array_generado = rng.choice(array_base, [3,2])
print(array_generado)

[[-7 15]
 [-7 -2]
 [ 0 20]]


## Ejercicio 1.14

Cómo extrar los valores de un array sin tener números repetidos

`np.unique(array_con_repetidos)`

In [30]:
array_repetidos = np.array([1,1,1,2,2,11,22,14,14,16,13,15,15,17,5,4,3,6,16,1,6,6,8,8,8,1,3,9,16,1,5,11,17,16,19,16,16,12,13,18,19,6,3,8,18,16])

In [31]:
print(array_repetidos)

[ 1  1  1  2  2 11 22 14 14 16 13 15 15 17  5  4  3  6 16  1  6  6  8  8
  8  1  3  9 16  1  5 11 17 16 19 16 16 12 13 18 19  6  3  8 18 16]


In [32]:
no_repetidos = np.unique(array_repetidos)
print(no_repetidos)

[ 1  2  3  4  5  6  8  9 11 12 13 14 15 16 17 18 19 22]
