# NUMPY


## Ejercicio 1.0

Importamos la librería numpy:

In [22]:
import numpy as np

## Ejercicio 1.1

Repaso de arrays:

In [23]:
#arreglo unidimensional
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) #le paso una lista y crea el array

In [24]:
print(array1) #imprimo el array

[1 2 3 4 5 6 7 8 9]


In [25]:
type(array1) #vemos el tipo de dato del array

numpy.ndarray

In [26]:
array2 = np.array([1, 2, 3, 4, 5, 6, 10, 11, 12]) #creo otro array

In [27]:
print(array1 + array2) #imprimo la suma

[ 2  4  6  8 10 12 17 19 21]


## Ejercicio 1.2

Creamos matrices:

In [28]:
#matriz de 2x2 bidimensional
matriz1 = np.array([
    [1,2],
    [3,4]
])

In [29]:
print(matriz1)

[[1 2]
 [3 4]]


In [30]:
#matriz 4x3 (filasxcolumnas)
matriz2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(matriz2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
#matriz 2x5
matriz3 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print(matriz3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Ejercicio 1.3

Operaciones con matrices.

In [32]:
matrizA = np.array([[1,2],[3,4]]) #matriz 2x2

In [33]:
matrizB = np.array([[1,2],[3,4]]) #matriz 2x2

In [34]:
#con matmul puedo calcular el producto de dos arrays
#antes lo calculábamos con matrizA * matrizB
print(np.matmul(matrizA, matrizB))

[[ 7 10]
 [15 22]]


In [35]:
#creamos una matriz
matriz_original = np.array([[1,2,3,4], [5,6,7,8]])
print(matriz_original)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
#calculamos su traspuesta 
matriz_traspuesta = np.transpose(matriz_original)

print(matriz_traspuesta)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Ejercicio 1.4

Calcular el determinante de una matriz.

In [37]:
matriz1 = np.array([[1,2],[3,4]])

In [38]:
determinante = np.linalg.det(matriz1)

In [39]:
print(matriz1)
print(determinante)

[[1 2]
 [3 4]]
-2.0000000000000004


## Ejercicio 1.5

Resolvemos ecuaciones lineales usando numpy.

5*X + 6*Y = 20

3*X + 8*Y = 34


In [40]:
#creamos una matriz con los coeficientes
coeficientes = np.array([
    [5,6],
    [3,8]
])

#creamos una matriz con las ordenadas al origen
ordenadas = np.array([20,34])

In [41]:
solucion = np.linalg.solve(coeficientes, ordenadas)
print(solucion)

[-2.  5.]


In [42]:
print(f"El valor de X es {round(solucion[0])}")
print(f"El valor de Y es {round(solucion[1])}")

El valor de X es -2
El valor de Y es 5


## Ejercicio 1.6

Vamos a trabajar con una matriz de tres dimensiones.

In [43]:
#creo la matriz de tres dimensiones
matriz_multidimensiones = np.array([
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [16,17,18,19],
            [20,21,22,23]
        ],
        [
            [24,25,26,27],
            [28,29,30,31],
            [32,33,34,35]
        ]
    ])

In [44]:
print(matriz_multidimensiones) #imprimo la matriz de tres dimensiones

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [45]:
#imprimo los valores de la matriz
matriz_multidimensiones[0, 0, 0] #[submatriz/pagina, fila, columna]

1

In [46]:
matriz_multidimensiones[0, 0, 2]

3

In [47]:
matriz_multidimensiones[0, 2, 1]

10

In [48]:
matriz_multidimensiones[2, 1, 3]

31

In [49]:
matriz_multidimensiones[1, 1, 0]

16

In [50]:
matriz_multidimensiones[2, 2, 2]

34

## Ejercicio 1.7

Podemos saber la cantidad de dimensiones que tiene cualquier arreglo:

`np.ndim(matriz)`

`matriz.ndim`

In [51]:
np.ndim(matriz_multidimensiones)

3

In [52]:
matriz_multidimensiones.ndim

3

## Ejercicio 1.8

Podemos conocer la forma del array:

`np.shape(matriz)`

`matriz.shape`

In [53]:
np.shape(matriz_multidimensiones) #paginas/submatriz, filas, columnas

(3, 3, 4)

In [54]:
matriz_multidimensiones.shape

(3, 3, 4)

## Ejercicio 1.9

Podemos ver la cantidad de elementos de un array:

`np.size(matriz)`

`matriz.size`

In [55]:
np.size(matriz_multidimensiones)

36

In [56]:
matriz_multidimensiones.size

36

## Ejercicio 1.10

Vamos a crear o recortar un nuevo array a partir de uno existente usando los indices.

In [57]:
array_unidimensional = np.array([1,2,3,5,1,5,3,7,3,8,3,6,3,7,2,6,7,2,6,7,2,5,6,7,2])

In [58]:
print(array_unidimensional)

[1 2 3 5 1 5 3 7 3 8 3 6 3 7 2 6 7 2 6 7 2 5 6 7 2]


In [59]:
array_unidimensional[0]

1

In [60]:
array_unidimensional[1]

2

In [61]:
array_unidimensional[-1]

2

In [62]:
array_unidimensional[-3]

6

In [63]:
array_unidimensional[0:4] #de la posicion 0 a la 4 (sin incluir el de la posicion 4) 

array([1, 2, 3, 5])

In [64]:
array_unidimensional[3:] #trae todo desde la posicion 3 y hacia la derecha

array([5, 1, 5, 3, 7, 3, 8, 3, 6, 3, 7, 2, 6, 7, 2, 6, 7, 2, 5, 6, 7, 2])

In [65]:
array_unidimensional[-3:] #los último tres valores

array([6, 7, 2])

In [66]:
array_unidimensional[:5] #trae hasta la posicion de llegada (del inicio hasta la posicion 5 sin inlcuirla, lo de la izquierda)

array([1, 2, 3, 5, 1])

In [67]:
array_unidimensional[:-10]

array([1, 2, 3, 5, 1, 5, 3, 7, 3, 8, 3, 6, 3, 7, 2])

## Ejercicio 1.11

Ordenar el array de forma ascendente, es decir de menor a mayor.

`np.sort(array_desordenado)`

In [68]:
array_desordenado = np.array([5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10])

In [69]:
array_ascendente = np.sort(array_desordenado)

In [70]:
print(array_ascendente)

[-10  -7  -6  -6  -5  -3  -2  -2  -1   0   1   2   3   3   4   4   5   5
   7   8   9  10  12  12  14  15  20]


## Ejercicio 1.12

Puedo reordenar el array en función de los índices, los valores que estaban primeros pasan a estar últimos y los que estaban últimos pasan a estar primeros.

`np.flip(mi_array)`

In [71]:
array_desordenado = np.array([5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10])

In [72]:
array_invertido = np.flip(array_desordenado)
print(array_invertido)

[ 10  -2   8   2   3   7  -5   4   0  -1  -6  20  15  14  12 -10   3  -3
   1   5  -6  12  -7   9  -2   4   5]


## Ejercicio 1.13

Vamos a crear un array con números aleatorios.

`np.random.default_rng()`

In [73]:
rng = np.random.default_rng() #construsctor

In [74]:
#arrays con valores aleatorios entre 0 y 1
rng.random(3)

array([0.87551048, 0.25358425, 0.68564749])

In [75]:
rng.random(5)

array([0.39562275, 0.15040746, 0.11961352, 0.33405455, 0.87436115])

In [76]:
#arrays con valores aleatorios entre números enteros
rng.integers(1,11,6) #valor mínimo inlcuisivo, valor máximo exclusivo, size

array([ 8, 10, 10,  2,  5,  8], dtype=int64)

In [77]:
rng.integers(-5,15,[4,3]) #matriz 4x3

array([[ 0,  8, 12],
       [10, 11,  7],
       [14,  4,  1],
       [ 5, 13,  0]], dtype=int64)

In [78]:
rng.integers(-20,100,[2,4,3]) #2 paginas, 4 filas, 3 columnas

array([[[  6,  66,  50],
        [ 99,  -6,  41],
        [ 17,  98,  74],
        [ 37,   4,  51]],

       [[  6,   5,  51],
        [  2, -14,  27],
        [ 52,  38,  77],
        [ 93,  29,  54]]], dtype=int64)

## Ejercicio 1.14

Generar un array con números aleatorios elegidos desde otro array:

`rng.choice(array, cantidad_elementos)`

In [79]:
array_base = [5,4,-2,9,-7,12,-6,5,1,-3,3,-10,12,14,15,20,-6,-1,0,4,-5,7,3,2,8,-2,10]
print(array_base)

[5, 4, -2, 9, -7, 12, -6, 5, 1, -3, 3, -10, 12, 14, 15, 20, -6, -1, 0, 4, -5, 7, 3, 2, 8, -2, 10]


In [80]:
array_generado = rng.choice(array_base, 3)
print(array_generado)

[10 -3  7]


In [81]:
array_generado = rng.choice(array_base, [3,2])
print(array_generado)

[[-5 -7]
 [ 8 12]
 [-2 -6]]


## Ejercicio 1.15

Cómo extrar los valores de un array sin tener números repetidos:

`np.unique(array_con_repetidos)`

In [82]:
array_repetidos = np.array([1,1,1,2,2,11,22,14,14,16,13,15,15,17,5,4,3,6,16,1,6,6,8,8,8,1,3,9,16,1,5,11,17,16,19,16,16,12,13,18,19,6,3,8,18,16])

In [83]:
print(array_repetidos)

[ 1  1  1  2  2 11 22 14 14 16 13 15 15 17  5  4  3  6 16  1  6  6  8  8
  8  1  3  9 16  1  5 11 17 16 19 16 16 12 13 18 19  6  3  8 18 16]


In [84]:
no_repetidos = np.unique(array_repetidos)
print(no_repetidos)

[ 1  2  3  4  5  6  8  9 11 12 13 14 15 16 17 18 19 22]


## PRÁCTICA



### Ejercicio 2.0

Tenemos una función cúbica con la forma (3x^3-7x^2+6*x+9):


In [90]:
def mi_funcion(x):
    return 3* x**3 - 7* x**2 + 6*x + 9

### Ejercicio 2.1
Calcular cuales serían los valores obtenidos al pasarle como argumentos los valores pares desde 0 a 20 incluyendo ambos. Guardar el resultado en un array.

In [93]:
resultados = []
for numero in range(0, 21, 2):
    valor = mi_funcion(numero)
    resultados.append(valor)

array_resultados = np.array(resultados)
print(array_resultados)

[    9    17   113   441  1145  2369  4257  6953 10601 15345 21329]


### Ejercicio 2.1

Al array que obtuvimos en la sección anterior:

. Calcula la media de los números en el array que contiene los valores calculados.

. Calcula la desviación estándar de los números en el array calculado.

. Encuentra el valor máximo y su índice en el array calculado.

. Crea un nuevo array array_cuadrados que contenga el cuadrado de cada número en calculado.

. Crear un array con la suma acumulativa (a1, a1+a2, a1+a2+a3, .....) de los elementos en array_cuadrados.

. Crear un array con la raiz 5ta de cada valor de array_cuadrados (redondear a 2 decimales).

. Imprimir los resultados obtenidos.

In [98]:
media = np.mean(array_resultados)
desviacion_estandar = np.std(array_resultados)
max = np.max(array_resultados)
indice_maximo = np.argmax(array_resultados)

array_cuadrado = np.square(array_resultados)
array_acumulativo = np.cumsum(array_resultados)
array_raiz_quinta = np.power(array_cuadrado, 1/5).round(2)

In [100]:
print(f"Media: {media}")
print(f"Desviación estandar: {desviacion_estandar}")
print(f"Valor maximo: {max}")
print(f"El valor máximo está en la posición: {indice_maximo}")
print(array_cuadrado)
print(array_acumulativo)
print(array_raiz_quinta)


Media: 5689.0
Desviación estandar: 6877.906658279102
Valor maximo: 21329
El valor máximo está en la posición: 10
[       81       289     12769    194481   1311025   5612161  18122049
  48344209 112381201 235469025 454926241]
[    9    26   139   580  1725  4094  8351 15304 25905 41250 62579]
[ 2.41  3.11  6.63 11.42 16.73 22.38 28.29 34.42 40.75 47.25 53.9 ]
