# PANDAS - DATAFRAMES

Los DataFames son objetos de Pandas que nos permiten guardar información estructurada en forma de tablas u hojas de cálculo.

Tienen **dos dimensiones**: filas y columnas.

Los DataFrames comparten muchas funciones con los índides, ya que cada columna de un DataFrame se la puede pensar como una serie.

## Ejercicio 1.0

Instalamos la versión pandas 2.2.2 y la instalamos

In [1]:
%pip install pandas==2.2.2

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np

## CREACIÓN 

### Ejercicio 1.1

Creación de un DataFrame a partir de listas.

In [3]:
#a partir de una listas se puede crear un DataFrame

lista_a0 = ["Sofia", "Garcia", 30, True]
lista_a2 = ["Veronica", "Gonzales", 20, False]
lista_a3 = ["Nicolas", "Perez", 40, True]
lista_a4 = ["Nadia", "Gutierrez", 15, False]

lista_nombres_encabezados = ["Nombre", "Apellido", "Edad", "Pago_matricula"]

In [4]:
#filas (cada uno de las listas de los alumnos), columnas
df_alumnos = pd.DataFrame(
    data=[lista_a0, lista_a2, lista_a3, lista_a4],
    columns=lista_nombres_encabezados
)
df_alumnos

Nombre   Apellido  Edad  Pago_matricula
0     Sofia     Garcia    30            True
1  Veronica   Gonzales    20           False
2   Nicolas      Perez    40            True
3     Nadia  Gutierrez    15           False

### Ejercicio 1.2

Crear un DataFrame a partir de un diccionario

In [5]:
dict_empleados = {
    "Nombre": ["Sofia", "Veronica", "Nicolas", "Nadia"],
    "Apellido": ["Garcia", "Gonzales", "Perez", "Gutierrez"],
    "Departamento": ["IT", "Contable", "IyD", "Legales"],
    "Sueldo": [5000, 2000, 5000, 3000], 
    "Facturacion": [True, False, True, True], 
}

In [6]:
#la info entra como columnas
df_empleados = pd.DataFrame(dict_empleados)
df_empleados


Nombre   Apellido Departamento  Sueldo  Facturacion
0     Sofia     Garcia           IT    5000         True
1  Veronica   Gonzales     Contable    2000        False
2   Nicolas      Perez          IyD    5000         True
3     Nadia  Gutierrez      Legales    3000         True

### Ejercicio 1.3

Creación de DataFrame a partir de un array

In [7]:
rng = np.random.default_rng() #constructor

In [8]:
array_6x3 = rng.integers(1, 20, (6, 3)) #min, max, size
print(array_6x3)

[[ 1 13 12]
 [14  8 19]
 [18 15 14]
 [13  1  4]
 [ 7 13  3]
 [14  6 11]]


In [9]:
lista_nombre_columnas=["nro_clientes", "nro_pedidos", "nro_devoluciones"]

In [10]:
df_array = pd.DataFrame(
    data=array_6x3,
    columns=lista_nombre_columnas
)
df_array

nro_clientes  nro_pedidos  nro_devoluciones
0             1           13                12
1            14            8                19
2            18           15                14
3            13            1                 4
4             7           13                 3
5            14            6                11

## INDICES

### Ejercicio 1.4

Así como en una serie, se pueden personalizar los índices

In [11]:
#DataFrame con info de vehículos a la venta en una concesionaria

lista_v0 = ["Fiat", "Uno", 1000, False]
lista_v1 = ["Fiat", "Palio", 2000, True]
lista_v2 = ["Ford", "Focus", 3000, True]
lista_v3 = ["Toyota", "Hilux", 8000, False]

lista_encabezados = ["Marca", "Modelo", "Precio", "Okm"]
lista_patentes = ["ASD123", "AF123AA", "TYP890", "AG677ER"]

In [12]:
df_concesionaria = pd.DataFrame(
    data=[lista_v0, lista_v1, lista_v2, lista_v3],
    columns=lista_encabezados,
    index=lista_patentes
)
df_concesionaria

Marca Modelo  Precio    Okm
ASD123     Fiat    Uno    1000  False
AF123AA    Fiat  Palio    2000   True
TYP890     Ford  Focus    3000   True
AG677ER  Toyota  Hilux    8000  False

### Ejercicio 1.5

Una vez que tenemos el DataFrame podemos indicar qué columna será el numero índice

In [14]:
dict_empleados = {
    "ID": ["A-123", "B-456", "C-789", "D-369"],
    "Nombre": ["Sofia", "Veronica", "Nicolas", "Nadia"],
    "Apellido": ["Garcia", "Gonzales", "Perez", "Gutierrez"],
    "Departamento": ["IT", "Contable", "IyD", "Legales"],
    "Sueldo": [5000, 2000, 5000, 3000], 
    "Facturacion": [True, False, True, True], 
}

In [15]:
df_empleados = pd.DataFrame(dict_empleados)
df_empleados

ID    Nombre   Apellido Departamento  Sueldo  Facturacion
0  A-123     Sofia     Garcia           IT    5000         True
1  B-456  Veronica   Gonzales     Contable    2000        False
2  C-789   Nicolas      Perez          IyD    5000         True
3  D-369     Nadia  Gutierrez      Legales    3000         True

In [16]:
df_empleados.set_index("ID")

Nombre   Apellido Departamento  Sueldo  Facturacion
ID                                                          
A-123     Sofia     Garcia           IT    5000         True
B-456  Veronica   Gonzales     Contable    2000        False
C-789   Nicolas      Perez          IyD    5000         True
D-369     Nadia  Gutierrez      Legales    3000         True

In [17]:
df_empleados #no se modificó el índice

ID    Nombre   Apellido Departamento  Sueldo  Facturacion
0  A-123     Sofia     Garcia           IT    5000         True
1  B-456  Veronica   Gonzales     Contable    2000        False
2  C-789   Nicolas      Perez          IyD    5000         True
3  D-369     Nadia  Gutierrez      Legales    3000         True

### Ejercicio 1.6

Si modificamos un DataFrame y queres que los cambios perdures se usa: `inplace`

In [18]:
df_empleados.set_index("ID", inplace=True)

In [19]:
df_empleados

Nombre   Apellido Departamento  Sueldo  Facturacion
ID                                                          
A-123     Sofia     Garcia           IT    5000         True
B-456  Veronica   Gonzales     Contable    2000        False
C-789   Nicolas      Perez          IyD    5000         True
D-369     Nadia  Gutierrez      Legales    3000         True