# INTRODUCCIÓN AL TRABAJO CON LIBRERIAS

Las librerias en Python son "cajas" que contienen un conjunto de funciones y variables que pueden ser utilizadas para realizar tareas específicas.

Podés usar las librerias simplemente llamándolos en tu programa cuando los necesites, y así aprovechar todas las funcionalidades que ofrecen sin tener que reescribir todo el código desde cero.



## IMPORTACIÓN DE LIBRERIAS

Sintaxis para importar una librería:

`import <nombre_libreria>`

También se puede asignarle un alias para nombrarla con mayor facilidad:

`import <nombre_libreria> as <alias>`

Si no vamos a usar toda la librería y no queremos sobrecargar la memoria, se puede importar solo un paquete en particular:

`from <nombre_libreria> import <nombre_paquete> as <alias>`

## INSTALACIÓN DE LIBRERÍAS

A la hora de trabajar con librerías es posible que no las tengamos instaladas ya que muchas son creadas por la comunidad, también puede que no estén incluidas en los archivos base de Python.

Para ellos se emplea el **pip**
. En la terminal (locas): `pip install <nombre_libreria>`
. En colab ejecutar: `!pip install <nombre_libreria>`

## MATH

La librería `math` permite realizar operaciones matemáticas más avanzadas y permite utilizar constantes matemáticas básicas para resolver problemas más complejos.

Incluye funciones para:

. Realizar cálculos trigonométricos

. Operaciones de álegbra lineal

. Funciones exponenciales y logarítmicas

### Ejercicio 1.0

Importamos la librería math

In [ ]:
import math

### Ejercicio 1.1

Calculamos el área de un círculo [pi*radio^2]

In [ ]:
radio = float(input("Ingrese el radio del círculo: "))
area = math.pi * radio**2

print(f"El área del círculo es: {area}")

Ingrese el radio del círculo: 10
El área del círculo es: 314.1592653589793


Redondeando el resultado a dos decimales

In [ ]:
area = round(area, 2)
print(f"El área del círculo es: {area}")


El área del círculo es: 314.16


### Ejercicio 1.2

Calculamos la hipotenusa de un triángulo rectángulo.

In [ ]:
cateto1 = float(input("Ingrese la logito del primer cateto: "))
cateto2 = float(input("Ingrese la logito del segundo cateto: "))
hipotenusa = round(math.sqrt(cateto1**2 + cateto2**2),2)

print(f"La longitud de la hipotenusa es: {hipotenusa}")

Ingrese la logito del primer cateto: 20
Ingrese la logito del segundo cateto: 5
La longitud de la hipotenusa es: 20.62


### Ejercicio 1.3

Calculadora de seno, coseno, tangente

In [ ]:
angulo_grados = float(input("Ingrese el valor del ángulo en grados: "))
angulo_radianes = math.radians(angulo_grados)


seno = math.sin(angulo_radianes)
coseno = math.cos(angulo_radianes)
tangente = math.tan(angulo_radianes)

print(f"Angulo en radianes: {angulo_radianes}")
print(f"Seno: {seno}")
print(f"Coseno: {coseno}")
print(f"Tangente: {tangente}")

Ingrese el valor del ángulo en grados: 30
Angulo en radianes: 0.5235987755982988
Seno: 0.49999999999999994
Coseno: 0.8660254037844387
Tangente: 0.5773502691896257


### Ejercicio 1.4

Cálculo de potencias

In [ ]:
base = float(input("Ingrese el numero que será la base en la operación: "))
exponente = float(input("Ingrese el exponente: "))

resultado = math.pow(base, exponente)

print(f"{base}^{exponente} = {round(resultado, 2)}")

Ingrese el numero que será la base en la operación: 2
Ingrese el exponente: 10
2.0^10.0 = 1024.0


## NUMPY

**NumPy** es una librería de Python que ayuda a trabjar con matrices y arreglos multidimencionales.

NumPy permite:

. Multiplicación de matrices/arreglos

. Inversión de matrices/arreglos

. Cálculo de funciones trigonométricas

. Procesamiento de datos

. Manipulación de matrices de manera rápida y eficiente

### Ejercicio 2.0

Importamos NumPy

In [ ]:
import numpy as np


### Ejercicio 2.1

Veamos las operaciones básicas con arrays (arreglos unidimensionales).

Los arrays son homogéneos y numéricos.

In [ ]:
lista_numerica = [10, 20, 30]

array1 = np.array([1, 2, 3, 4, 5]) #creamos un array de numeros
array2 = np.array(lista_numerica)

print(array1)
print(array2)

[1 2 3 4 5]
[10 20 30]


In [ ]:
type(lista_numerica), type(array2)

(list, numpy.ndarray)

In [ ]:
array3 = np.array([6, 7, 8, 9, 10])

suma = array1 + array3
resta = array1 - array3
multiplicacion = array1 * array3
division = array1 / array3

print(array1)
print(array3)
print(f"Suma: {suma}")
print(f"Resta: {resta}")
print(f"Multiplicación: {multiplicacion}")
print(f"División: {division}")

[1 2 3 4 5]
[ 6  7  8  9 10]
Suma: [ 7  9 11 13 15]
Resta: [-5 -5 -5 -5 -5]
Multiplicación: [ 6 14 24 36 50]
División: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
producto_escalar = np.dot(array1, array3) #producto escalar entre los arrays
print(producto_escalar)


130


### Ejercicio 2.2

Creamos matrices.

In [ ]:
#matriz identidad
matriz_identidad = np.eye(4)
print(matriz_identidad)

In [35]:
matriz_ceros = np.zeros((2,4))
print(matriz_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
matriz_unos = np.ones((3,3))
print(matriz_unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[10, 14], [18, 72]])

print(matriz1)
print(matriz2)

[[1 2]
 [3 4]]
[[10 14]
 [18 72]]


### Ejercicio 2.3

Operaciones con matrices

In [ ]:
producto_matrices = matriz1 * matriz2
traspuesta1 = np.transpose(matriz1)
traspuesta2 = np.transpose(matriz2)
determinante1 = np.linalg.det(matriz1)
determinante2 = np.linalg.det(matriz2)


print("Producto matricial")
print(producto_matrices)
print("Traspuesta de matriz1")
print(traspuesta1)
print("Traspuesta de matriz2")
print(traspuesta2)
print("Determinante de matriz1")
print(determinante1)
print("Determinante de matriz2")
print(determinante2)

Producto matricial
[[ 10  28]
 [ 54 288]]
Traspuesta de matriz1
[[1 3]
 [2 4]]
Traspuesta de matriz2
[[10 18]
 [14 72]]
Determinante de matriz1
-2.0000000000000004
Determinante de matriz2
468.00000000000017
