# PANDAS - DATAFRAME

Los DataFames son objetos de Pandas que nos permiten guardar información estructurada en forma de tablas u hojas de cálculo.

Tienen **dos dimensiones**: filas y columnas.

Los DataFrames comparten muchas funciones con los índides, ya que cada columna de un DataFrame se la puede pensar como una serie.

## Ejercicio 1.0

Instalamos la versión pandas 2.2.2 y la instalamos

In [64]:
%pip install pandas==2.2.2

Note: you may need to restart the kernel to use updated packages.


In [65]:
import pandas as pd
import numpy as np

## CREACIÓN 

### Ejercicio 1.1

Creación de un DataFrame a partir de listas.

In [66]:
#a partir de una listas se puede crear un DataFrame

lista_a0 = ["Sofia", "Garcia", 30, True]
lista_a2 = ["Veronica", "Gonzales", 20, False]
lista_a3 = ["Nicolas", "Perez", 40, True]
lista_a4 = ["Nadia", "Gutierrez", 15, False]

lista_nombres_encabezados = ["Nombre", "Apellido", "Edad", "Pago_matricula"]

In [67]:
#filas (cada uno de las listas de los alumnos), columnas
df_alumnos = pd.DataFrame(
    data=[lista_a0, lista_a2, lista_a3, lista_a4],
    columns=lista_nombres_encabezados
)
df_alumnos

Nombre   Apellido  Edad  Pago_matricula
0     Sofia     Garcia    30            True
1  Veronica   Gonzales    20           False
2   Nicolas      Perez    40            True
3     Nadia  Gutierrez    15           False

### Ejercicio 1.2

Crear un DataFrame a partir de un diccionario

In [68]:
dict_empleados = {
    "Nombre": ["Sofia", "Veronica", "Nicolas", "Nadia"],
    "Apellido": ["Garcia", "Gonzales", "Perez", "Gutierrez"],
    "Departamento": ["IT", "Contable", "IyD", "Legales"],
    "Sueldo": [5000, 2000, 5000, 3000], 
    "Facturacion": [True, False, True, True], 
}

In [69]:
#la info entra como columnas
df_empleados = pd.DataFrame(dict_empleados)
df_empleados


Nombre   Apellido Departamento  Sueldo  Facturacion
0     Sofia     Garcia           IT    5000         True
1  Veronica   Gonzales     Contable    2000        False
2   Nicolas      Perez          IyD    5000         True
3     Nadia  Gutierrez      Legales    3000         True

### Ejercicio 1.3

Creación de DataFrame a partir de un array

In [70]:
rng = np.random.default_rng() #constructor

In [71]:
array_6x3 = rng.integers(1, 20, (6, 3)) #min, max, size
print(array_6x3)

[[ 9 15  3]
 [19 11 17]
 [ 3  8 11]
 [ 8 10  7]
 [12 14 15]
 [12  8  1]]


In [72]:
lista_nombre_columnas=["nro_clientes", "nro_pedidos", "nro_devoluciones"]

In [73]:
df_array = pd.DataFrame(
    data=array_6x3,
    columns=lista_nombre_columnas
)
df_array

nro_clientes  nro_pedidos  nro_devoluciones
0             9           15                 3
1            19           11                17
2             3            8                11
3             8           10                 7
4            12           14                15
5            12            8                 1

## INDICES

### Ejercicio 1.4

Así como en una serie, se pueden personalizar los índices

In [74]:
#DataFrame con info de vehículos a la venta en una concesionaria

lista_v0 = ["Fiat", "Uno", 1000, False]
lista_v1 = ["Fiat", "Palio", 2000, True]
lista_v2 = ["Ford", "Focus", 3000, True]
lista_v3 = ["Toyota", "Hilux", 8000, False]

lista_encabezados = ["Marca", "Modelo", "Precio", "Okm"]
lista_patentes = ["ASD123", "AF123AA", "TYP890", "AG677ER"]

In [75]:
df_concesionaria = pd.DataFrame(
    data=[lista_v0, lista_v1, lista_v2, lista_v3],
    columns=lista_encabezados,
    index=lista_patentes
)
df_concesionaria

Marca Modelo  Precio    Okm
ASD123     Fiat    Uno    1000  False
AF123AA    Fiat  Palio    2000   True
TYP890     Ford  Focus    3000   True
AG677ER  Toyota  Hilux    8000  False

### Ejercicio 1.5

Una vez que tenemos el DataFrame podemos indicar qué columna será el numero índice

In [76]:
dict_empleados = {
    "ID": ["A-123", "B-456", "C-789", "D-369"],
    "Nombre": ["Sofia", "Veronica", "Nicolas", "Nadia"],
    "Apellido": ["Garcia", "Gonzales", "Perez", "Gutierrez"],
    "Departamento": ["IT", "Contable", "IyD", "Legales"],
    "Sueldo": [5000, 2000, 5000, 3000], 
    "Facturacion": [True, False, True, True], 
}

In [77]:
df_empleados = pd.DataFrame(dict_empleados)
df_empleados

ID    Nombre   Apellido Departamento  Sueldo  Facturacion
0  A-123     Sofia     Garcia           IT    5000         True
1  B-456  Veronica   Gonzales     Contable    2000        False
2  C-789   Nicolas      Perez          IyD    5000         True
3  D-369     Nadia  Gutierrez      Legales    3000         True

In [78]:
df_empleados.set_index("ID")

Nombre   Apellido Departamento  Sueldo  Facturacion
ID                                                          
A-123     Sofia     Garcia           IT    5000         True
B-456  Veronica   Gonzales     Contable    2000        False
C-789   Nicolas      Perez          IyD    5000         True
D-369     Nadia  Gutierrez      Legales    3000         True

In [79]:
df_empleados #no se modificó el índice

ID    Nombre   Apellido Departamento  Sueldo  Facturacion
0  A-123     Sofia     Garcia           IT    5000         True
1  B-456  Veronica   Gonzales     Contable    2000        False
2  C-789   Nicolas      Perez          IyD    5000         True
3  D-369     Nadia  Gutierrez      Legales    3000         True

### Ejercicio 1.6

Si modificamos un DataFrame y queres que los cambios perdures se usa: `inplace`

In [80]:
df_empleados.set_index("ID", inplace=True)

In [81]:
df_empleados

Nombre   Apellido Departamento  Sueldo  Facturacion
ID                                                          
A-123     Sofia     Garcia           IT    5000         True
B-456  Veronica   Gonzales     Contable    2000        False
C-789   Nicolas      Perez          IyD    5000         True
D-369     Nadia  Gutierrez      Legales    3000         True

### Ejercicio 1.7

En los DataFrames podemos tener un índice basado en fechas

In [82]:
dias = pd.date_range(
    start="2024-01-01",
    end="2024-04-27"
)
dias

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2024-04-18', '2024-04-19', '2024-04-20', '2024-04-21',
               '2024-04-22', '2024-04-23', '2024-04-24', '2024-04-25',
               '2024-04-26', '2024-04-27'],
              dtype='datetime64[ns]', length=118, freq='D')

In [83]:
df_resumen_ventas = pd.DataFrame(
    data= {
        "nro_ventas": rng.integers(1, 21, len(dias)),
        "costos_usd": rng.integers(100, 2001, len(dias)), 
        "ganancias": rng.random(len(dias)).round(2)
    },
    index=dias
)
df_resumen_ventas

nro_ventas  costos_usd  ganancias
2024-01-01          15         229       0.88
2024-01-02           8        1657       0.88
2024-01-03          16         767       0.70
2024-01-04           9        1360       0.67
2024-01-05          18         687       0.21
...                ...         ...        ...
2024-04-23          18        1786       0.50
2024-04-24          10        1225       0.69
2024-04-25          17         855       0.68
2024-04-26          13         945       0.48
2024-04-27           3        1315       0.43

[118 rows x 3 columns]

## FUNCIONES Y MÉTODOS

### Ejercicio 1.8

In [84]:
df_resumen_ventas.head() #trae los primeros cinco

nro_ventas  costos_usd  ganancias
2024-01-01          15         229       0.88
2024-01-02           8        1657       0.88
2024-01-03          16         767       0.70
2024-01-04           9        1360       0.67
2024-01-05          18         687       0.21

In [85]:
df_resumen_ventas.tail() #trea los últimos cinco

nro_ventas  costos_usd  ganancias
2024-04-23          18        1786       0.50
2024-04-24          10        1225       0.69
2024-04-25          17         855       0.68
2024-04-26          13         945       0.48
2024-04-27           3        1315       0.43

In [86]:
df_resumen_ventas.describe() #resumen estadístico

nro_ventas   costos_usd   ganancias
count  118.000000   118.000000  118.000000
mean    11.500000  1035.618644    0.519576
std      5.575818   518.127973    0.273009
min      1.000000   130.000000    0.020000
25%      7.000000   650.500000    0.312500
50%     11.000000  1023.000000    0.490000
75%     16.750000  1465.500000    0.760000
max     20.000000  1983.000000    0.990000

El 75% de los días tuve 15 ventas o menos o solamente el 25% de los días tuve 15 ventas o más (tercer cuartil)

El 25% de los días tuve costos menores a 594 UDS o el 75% de los días tuve un costos mayores a 594 USD (primer cuartil)

In [87]:
df_resumen_ventas.info() #me permite ver si tengo un problema con mis tipos de datos

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 118 entries, 2024-01-01 to 2024-04-27
Freq: D
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   nro_ventas  118 non-null    int64  
 1   costos_usd  118 non-null    int64  
 2   ganancias   118 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 3.7 KB


In [88]:
df_resumen_ventas.shape #indica la forma de la tabla

(118, 3)

### Ejercicio 1.9

Puedo ver a cada columna como una Series.

In [89]:
df_resumen_ventas.nro_ventas

2024-01-01    15
2024-01-02     8
2024-01-03    16
2024-01-04     9
2024-01-05    18
              ..
2024-04-23    18
2024-04-24    10
2024-04-25    17
2024-04-26    13
2024-04-27     3
Freq: D, Name: nro_ventas, Length: 118, dtype: int64

Me trae la columna como una series.

Entonces podemos utilizar el sistema de filtrado de las series en mi DataFrame.

In [90]:
#quiero saber que días tuve 15 ventas o más
df_resumen_ventas[df_resumen_ventas.nro_ventas >= 15]

nro_ventas  costos_usd  ganancias
2024-01-01          15         229       0.88
2024-01-03          16         767       0.70
2024-01-05          18         687       0.21
2024-01-07          19         238       0.29
2024-01-10          20         176       0.11
2024-01-13          19         236       0.41
2024-01-18          20         803       0.76
2024-01-20          15        1905       0.36
2024-01-22          16         824       0.04
2024-01-23          15         996       0.22
2024-01-24          15        1503       0.17
2024-01-30          19        1380       0.14
2024-01-31          20        1478       0.87
2024-02-03          17         281       0.69
2024-02-05          17        1019       0.47
2024-02-10          18         969       0.31
2024-02-12          20        1694       0.61
2024-02-14          20        1199       0.45
2024-02-15          18         709       0.41
2024-02-18          20        1475       0.13
2024-02-22          15        1428       0.33
2024-02-24          16        1486       0.83
2024-02-25          18        1741       0.94
2024-03-04          19        1066       0.90
2024-03-06          17         283       0.61
2024-03-07          19         836       0.87
2024-03-10          16        1222       0.92
2024-03-11          20        1983       0.48
2024-03-16          17         280       0.69
2024-03-18          16         282       0.43
2024-03-27          18        1363       0.76
2024-03-28          19        1856       0.91
2024-03-30          19        1587       0.12
2024-04-01          18         211       0.91
2024-04-06          16        1036       0.79
2024-04-07          18         679       0.21
2024-04-09          16        1019       0.88
2024-04-14          20        1202       0.32
2024-04-16          19        1034       0.57
2024-04-19          18        1014       0.55
2024-04-21          16        1592       0.84
2024-04-23          18        1786       0.50
2024-04-25          17         855       0.68

Podemos hacer un criterio de filtado cruzado.

In [91]:
#días en donde las ventas dejaron una ganancia mayor o igual al 90% con costos menores a 500 usd
df_resumen_ventas[(df_resumen_ventas.ganancias >= 0.90) & (df_resumen_ventas.costos_usd < 500)]

nro_ventas  costos_usd  ganancias
2024-01-08           8         440       0.97
2024-02-16          11         469       0.90
2024-04-01          18         211       0.91
2024-04-20           7         219       0.99

### Ejercicio 1.10

Más funciones y métodos

In [92]:
#iloc : localiza un indice y trae su info

df_resumen_ventas.iloc[20]

nro_ventas      7.00
costos_usd    233.00
ganancias       0.66
Name: 2024-01-21 00:00:00, dtype: float64

In [93]:
df_resumen_ventas.iloc[20:40]

nro_ventas  costos_usd  ganancias
2024-01-21           7         233       0.66
2024-01-22          16         824       0.04
2024-01-23          15         996       0.22
2024-01-24          15        1503       0.17
2024-01-25          11         726       0.35
2024-01-26          11        1352       0.53
2024-01-27          12         538       0.05
2024-01-28           2        1064       0.81
2024-01-29           4        1930       0.18
2024-01-30          19        1380       0.14
2024-01-31          20        1478       0.87
2024-02-01           6         314       0.67
2024-02-02           5         888       0.63
2024-02-03          17         281       0.69
2024-02-04          11        1435       0.83
2024-02-05          17        1019       0.47
2024-02-06          11        1888       0.39
2024-02-07           9        1082       0.60
2024-02-08           9         545       0.16
2024-02-09           6         972       0.91

In [94]:
df_resumen_ventas.iloc[:20]

nro_ventas  costos_usd  ganancias
2024-01-01          15         229       0.88
2024-01-02           8        1657       0.88
2024-01-03          16         767       0.70
2024-01-04           9        1360       0.67
2024-01-05          18         687       0.21
2024-01-06          11         259       0.28
2024-01-07          19         238       0.29
2024-01-08           8         440       0.97
2024-01-09           9        1124       0.34
2024-01-10          20         176       0.11
2024-01-11          14         968       0.77
2024-01-12           9         296       0.10
2024-01-13          19         236       0.41
2024-01-14           1        1027       0.96
2024-01-15           9         719       0.30
2024-01-16          14         537       0.84
2024-01-17          13        1133       0.62
2024-01-18          20         803       0.76
2024-01-19          13        1374       0.47
2024-01-20          15        1905       0.36

In [95]:
#Veamos cómo ordenar nuestro DataFrame, hay que indicar qué columna se usa para ordenar

df_resumen_ventas.sort_values(by="nro_ventas") #de menor a mayor

nro_ventas  costos_usd  ganancias
2024-04-18           1        1493       0.83
2024-01-14           1        1027       0.96
2024-01-28           2        1064       0.81
2024-04-22           2        1216       0.40
2024-04-17           2        1819       0.50
...                ...         ...        ...
2024-01-31          20        1478       0.87
2024-02-18          20        1475       0.13
2024-02-14          20        1199       0.45
2024-04-14          20        1202       0.32
2024-01-10          20         176       0.11

[118 rows x 3 columns]

In [96]:
df_resumen_ventas.sort_values(by="nro_ventas", ascending=False) #de mayor a menor

nro_ventas  costos_usd  ganancias
2024-02-12          20        1694       0.61
2024-02-18          20        1475       0.13
2024-01-18          20         803       0.76
2024-02-14          20        1199       0.45
2024-01-31          20        1478       0.87
...                ...         ...        ...
2024-04-17           2        1819       0.50
2024-04-22           2        1216       0.40
2024-02-17           2        1860       0.35
2024-01-14           1        1027       0.96
2024-04-18           1        1493       0.83

[118 rows x 3 columns]

In [97]:
#creamos un DataFrame con columnas categoricas

dict_concesionaria = {
    "marca": ["Toyota", "Honda", "Ford", "Chevrolet", "Volkswagen", "BMW", "Mercedes-Benz", "Audi", "Hyundai", "Kia", "Mazda", "Nissan", "Subaru", "Volvo", "Tesla"],
    "modelo": ["Corolla", "Civic", "Focus", "Cruze", "Golf", "X5", "C-Class", "A4", "Elantra", "Sportage", "3", "Altima", "Impreza", "S60", "Model S"],
    "precio": [25000, 23000, 22000, 21000, 20000, 60000, 55000, 50000, 18000, 19000, 24000, 22000, 28000, 45000, 70000],
    "0km": [True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
}

df_concesionaria = pd.DataFrame(dict_concesionaria)
df_concesionaria

marca    modelo  precio    0km
0          Toyota   Corolla   25000   True
1           Honda     Civic   23000  False
2            Ford     Focus   22000   True
3       Chevrolet     Cruze   21000  False
4      Volkswagen      Golf   20000   True
5             BMW        X5   60000  False
6   Mercedes-Benz   C-Class   55000   True
7            Audi        A4   50000  False
8         Hyundai   Elantra   18000   True
9             Kia  Sportage   19000  False
10          Mazda         3   24000   True
11         Nissan    Altima   22000  False
12         Subaru   Impreza   28000   True
13          Volvo       S60   45000  False
14          Tesla   Model S   70000   True

In [98]:
#Qué BMW está a la venta?

df_concesionaria[df_concesionaria.marca=="BMW"]

marca modelo  precio    0km
5   BMW     X5   60000  False

In [99]:
#necesitamos saber qué Ford 0km está a la venta 
df_concesionaria[(df_concesionaria.marca=="Ford") & (df_concesionaria.0km==True)]

SyntaxError: invalid decimal literal (1122025143.py, line 2)

In [100]:
df_concesionaria[(df_concesionaria["marca"]=="Ford") & df_concesionaria["0km"]==True]

marca modelo  precio   0km
2  Ford  Focus   22000  True

## RENOMBRAR COLUMNAS E ÍNDICES

### Ejercicio 1.11

In [101]:
#renombramos la columna 0km

df_concesionaria.rename(
    columns={"0km": "nuevo"}, #la key va a ser igual al nombre de la columna actual y el value será el nuevo nombre
    inplace=True
)
df_concesionaria

marca    modelo  precio  nuevo
0          Toyota   Corolla   25000   True
1           Honda     Civic   23000  False
2            Ford     Focus   22000   True
3       Chevrolet     Cruze   21000  False
4      Volkswagen      Golf   20000   True
5             BMW        X5   60000  False
6   Mercedes-Benz   C-Class   55000   True
7            Audi        A4   50000  False
8         Hyundai   Elantra   18000   True
9             Kia  Sportage   19000  False
10          Mazda         3   24000   True
11         Nissan    Altima   22000  False
12         Subaru   Impreza   28000   True
13          Volvo       S60   45000  False
14          Tesla   Model S   70000   True

In [102]:
#renombramos varias columnas
df_concesionaria.rename(
    columns={"marca": "MARCA", 
             "modelo": "MODELO", 
             "precio": "PRECIO_USD",
             "nuevo": "NUEVO"
             },
    inplace=True
)
df_concesionaria

MARCA    MODELO  PRECIO_USD  NUEVO
0          Toyota   Corolla       25000   True
1           Honda     Civic       23000  False
2            Ford     Focus       22000   True
3       Chevrolet     Cruze       21000  False
4      Volkswagen      Golf       20000   True
5             BMW        X5       60000  False
6   Mercedes-Benz   C-Class       55000   True
7            Audi        A4       50000  False
8         Hyundai   Elantra       18000   True
9             Kia  Sportage       19000  False
10          Mazda         3       24000   True
11         Nissan    Altima       22000  False
12         Subaru   Impreza       28000   True
13          Volvo       S60       45000  False
14          Tesla   Model S       70000   True

### Ejercicio 1.12

Así como podemos renombrar las columnas, podemos renombrear o asignar un nombre a los índices

In [103]:
df_concesionaria.index.rename(name="ID", inplace=True)
df_concesionaria

MARCA    MODELO  PRECIO_USD  NUEVO
ID                                            
0          Toyota   Corolla       25000   True
1           Honda     Civic       23000  False
2            Ford     Focus       22000   True
3       Chevrolet     Cruze       21000  False
4      Volkswagen      Golf       20000   True
5             BMW        X5       60000  False
6   Mercedes-Benz   C-Class       55000   True
7            Audi        A4       50000  False
8         Hyundai   Elantra       18000   True
9             Kia  Sportage       19000  False
10          Mazda         3       24000   True
11         Nissan    Altima       22000  False
12         Subaru   Impreza       28000   True
13          Volvo       S60       45000  False
14          Tesla   Model S       70000   True

## AGREGAR INFORMACIÓN AL DATAFRAME

### Ejercicio 1.13

Vamos a concatenar DataFrame

In [104]:
#queremos agregar un nuevo vehículo a la tabla de vehículos a la venta
df_nuevo_vehículo = pd.DataFrame(
    data=[
        ["Toyota", "Hilux", 1400, False]
    ],
    columns=["MARCA", "MODELO",	"PRECIO_USD", "NUEVO"]     
)
df_nuevo_vehículo

MARCA MODELO  PRECIO_USD  NUEVO
0  Toyota  Hilux        1400  False

In [105]:
#uso concat para añadir la nueva fila

df_concesionaria = pd.concat([df_concesionaria, df_nuevo_vehículo], ignore_index=True)

In [106]:
df_concesionaria

MARCA    MODELO  PRECIO_USD  NUEVO
0          Toyota   Corolla       25000   True
1           Honda     Civic       23000  False
2            Ford     Focus       22000   True
3       Chevrolet     Cruze       21000  False
4      Volkswagen      Golf       20000   True
5             BMW        X5       60000  False
6   Mercedes-Benz   C-Class       55000   True
7            Audi        A4       50000  False
8         Hyundai   Elantra       18000   True
9             Kia  Sportage       19000  False
10          Mazda         3       24000   True
11         Nissan    Altima       22000  False
12         Subaru   Impreza       28000   True
13          Volvo       S60       45000  False
14          Tesla   Model S       70000   True
15         Toyota     Hilux        1400  False

In [107]:
#podemos añadir un DataFrame con más información

dict_importados = {
    "MARCA": ["Toyota", "Honda", "Ford"],
    "MODELO": ["Corolla", "Civic", "Focus"],
    "PRECIO_USD": [25000, 23000, 22000],
    "NUEVO": [True, False, True]
}
df_importados = pd.DataFrame(dict_importados)
df_importados

MARCA   MODELO  PRECIO_USD  NUEVO
0  Toyota  Corolla       25000   True
1   Honda    Civic       23000  False
2    Ford    Focus       22000   True

In [108]:
df_concesionaria = pd.concat([df_concesionaria, df_importados], ignore_index=True)

In [109]:
df_concesionaria

MARCA    MODELO  PRECIO_USD  NUEVO
0          Toyota   Corolla       25000   True
1           Honda     Civic       23000  False
2            Ford     Focus       22000   True
3       Chevrolet     Cruze       21000  False
4      Volkswagen      Golf       20000   True
5             BMW        X5       60000  False
6   Mercedes-Benz   C-Class       55000   True
7            Audi        A4       50000  False
8         Hyundai   Elantra       18000   True
9             Kia  Sportage       19000  False
10          Mazda         3       24000   True
11         Nissan    Altima       22000  False
12         Subaru   Impreza       28000   True
13          Volvo       S60       45000  False
14          Tesla   Model S       70000   True
15         Toyota     Hilux        1400  False
16         Toyota   Corolla       25000   True
17          Honda     Civic       23000  False
18           Ford     Focus       22000   True

In [110]:
#hay que tener mucho cuidado al concatenar, los nombres de las columnas deben coincidir

dict_importados2 = {
    "fabricante": ["Toyota", "Honda", "Ford"],
    "modelo": ["Corolla", "Civic", "Focus"],
    "costo_usd": [25000, 23000, 22000],
    "0km": [True, False, True]
}
df_importados2 = pd.DataFrame(dict_importados2)
df_importados2

fabricante   modelo  costo_usd    0km
0     Toyota  Corolla      25000   True
1      Honda    Civic      23000  False
2       Ford    Focus      22000   True

In [111]:
df_concesionaria2 = pd.concat([df_concesionaria, df_importados2], ignore_index=True)
df_concesionaria2

MARCA    MODELO  PRECIO_USD  NUEVO fabricante   modelo  costo_usd  \
0          Toyota   Corolla     25000.0   True        NaN      NaN        NaN   
1           Honda     Civic     23000.0  False        NaN      NaN        NaN   
2            Ford     Focus     22000.0   True        NaN      NaN        NaN   
3       Chevrolet     Cruze     21000.0  False        NaN      NaN        NaN   
4      Volkswagen      Golf     20000.0   True        NaN      NaN        NaN   
5             BMW        X5     60000.0  False        NaN      NaN        NaN   
6   Mercedes-Benz   C-Class     55000.0   True        NaN      NaN        NaN   
7            Audi        A4     50000.0  False        NaN      NaN        NaN   
8         Hyundai   Elantra     18000.0   True        NaN      NaN        NaN   
9             Kia  Sportage     19000.0  False        NaN      NaN        NaN   
10          Mazda         3     24000.0   True        NaN      NaN        NaN   
11         Nissan    Altima     22000.0  False        NaN      NaN        NaN   
12         Subaru   Impreza     28000.0   True        NaN      NaN        NaN   
13          Volvo       S60     45000.0  False        NaN      NaN        NaN   
14          Tesla   Model S     70000.0   True        NaN      NaN        NaN   
15         Toyota     Hilux      1400.0  False        NaN      NaN        NaN   
16         Toyota   Corolla     25000.0   True        NaN      NaN        NaN   
17          Honda     Civic     23000.0  False        NaN      NaN        NaN   
18           Ford     Focus     22000.0   True        NaN      NaN        NaN   
19            NaN       NaN         NaN    NaN     Toyota  Corolla    25000.0   
20            NaN       NaN         NaN    NaN      Honda    Civic    23000.0   
21            NaN       NaN         NaN    NaN       Ford    Focus    22000.0   

      0km  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
5     NaN  
6     NaN  
7     NaN  
8     NaN  
9     NaN  
10    NaN  
11    NaN  
12    NaN  
13    NaN  
14    NaN  
15    NaN  
16    NaN  
17    NaN  
18    NaN  
19   True  
20  False  
21   True

### Ejercicio 1.14

Veamos cómo utilizar el merge

In [112]:
df_empleados = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Sueldo': [5000, 6000, 4500, 5500],
    'Edad': [30, 35, 28, 40],
    'Cargo': ['Analista', 'Gerente', 'Analista', 'Director'],
    'Facturacion': [True, True, False, True],
    'Antiguedad': [3, 5, 2, 8],
    'Departamento_ID':[1,2,4,3]
})
df_departamentos = pd.DataFrame({
    'Departamento_ID':[1,2,3],
    'Nombre':["Sales","IT","HR"],
    'Piso':[1,2,2],
    'Rotacion_24hs':[True,True,False]
})

In [113]:
df_empleados

ID  Sueldo  Edad     Cargo  Facturacion  Antiguedad  Departamento_ID
0  101    5000    30  Analista         True           3                1
1  102    6000    35   Gerente         True           5                2
2  103    4500    28  Analista        False           2                4
3  104    5500    40  Director         True           8                3

In [114]:
df_departamentos

Departamento_ID Nombre  Piso  Rotacion_24hs
0                1  Sales     1           True
1                2     IT     2           True
2                3     HR     2          False

In [115]:
df_empleados_cobro = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Sueldo': [5000, 6000, 4500, 5500],
    'Facturacion': [True, True, False, True],
    'Antiguedad': [3, 5, 2, 8]
})

df_empleados_info = pd.DataFrame({
    'ID': [101, 102, 105, 106],
    'Edad': [31, 36, 29, 41],
    'Cargo': ['Analista', 'Gerente', 'Analista', 'Director'],
    'Nombre':["Pedro","Camila",'Mariano','Federico']
})

In [116]:
df_empleados_cobro

ID  Sueldo  Facturacion  Antiguedad
0  101    5000         True           3
1  102    6000         True           5
2  103    4500        False           2
3  104    5500         True           8

In [117]:
df_empleados_info

ID  Edad     Cargo    Nombre
0  101    31  Analista     Pedro
1  102    36   Gerente    Camila
2  105    29  Analista   Mariano
3  106    41  Director  Federico

In [ ]:
#Inner merge